name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4
  - name: Build
    run: g++ -std=c++11 -o beam_calculator main.cpp
  - name: Test Run
    run: ./beam_calculator < /dev/null || true
